# Generated by Django 4.2.7 on 2026-01-26 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='구역 이름 (예: 한강공원)', max_length=200)),
                ('city', models.CharField(help_text='도시 (예: 서울)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='구역 설명')),
                ('bounds', models.JSONField(default=dict, help_text='게임 영역 경계 (GeoJSON polygon)')),
                ('h3_resolution', models.IntegerField(default=8, help_text='H3 해상도 (기본: 8)')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부 (비활성화 시 선택 불가)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_areas',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.CharField(choices=[('A', 'A팀'), ('B', 'B팀')], default='A', help_text='팀', max_length=1)),
                ('is_host', models.BooleanField(default=False, help_text='방장 여부')),
                ('is_recording', models.BooleanField(default=False, help_text='현재 기록 중인지')),
                ('paintball_count', models.IntegerField(default=0, help_text='페인트볼 개수')),
                ('super_paintball_count', models.IntegerField(default=0, help_text='슈퍼 페인트볼 개수')),
                ('paintball_gauge', models.IntegerField(default=0, help_text='페인트볼 게이지 (0-100)')),
                ('consecutive_attendance_days', models.IntegerField(default=0, help_text='연속 출석일')),
                ('last_attendance_date', models.DateField(blank=True, help_text='마지막 출석일', null=True)),
                ('last_lat', models.FloatField(blank=True, help_text='마지막 위도', null=True)),
                ('last_lng', models.FloatField(blank=True, help_text='마지막 경도', null=True)),
                ('last_h3_id', models.CharField(blank=True, db_index=True, help_text='마지막 H3 ID', max_length=20, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, help_text='마지막 위치 업데이트 시간', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='방 이름', max_length=200)),
                ('total_participants', models.IntegerField(default=4, help_text='총 인원수 (짝수, A팀 절반 + B팀 절반)')),
                ('start_date', models.DateField(help_text='게임 시작 날짜')),
                ('end_date', models.DateField(help_text='게임 종료 날짜')),
                ('current_hex_ownerships', models.JSONField(blank=True, default=dict, help_text='현재 hex 점령 상태 {h3_id: {team: "A"|"B", user_id, claimed_at}}')),
                ('status', models.CharField(choices=[('ready', '준비'), ('active', '진행중'), ('finished', '완료')], db_index=True, default='ready', help_text='방 상태', max_length=20)),
                ('invite_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('winner_team', models.CharField(blank=True, choices=[('A', 'A팀'), ('B', 'B팀')], help_text='승리 팀', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='방장', on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('game_area', models.ForeignKey(help_text='선택한 게임 구역', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.gamearea')),
                ('mvp', models.ForeignKey(blank=True, help_text='게임 종료 시 MVP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField(default=0, help_text='달린 시간 (초)')),
                ('distance_meters', models.FloatField(default=0.0, help_text='달린 거리 (미터)')),
                ('avg_pace_seconds_per_km', models.FloatField(blank=True, help_text='평균 페이스 (초/km)', null=True)),
                ('started_at', models.DateTimeField(help_text='기록 시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, help_text='기록 종료 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_records', to='rooms.participant')),
                ('room', models.ForeignKey(blank=True, help_text='관련 방 (방 밖에서 뛸 수도 있음)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='running_records', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'running_records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gamearea',
            index=models.Index(fields=['city', 'is_active'], name='game_areas_city_15050f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamearea',
            constraint=models.CheckConstraint(check=models.Q(('h3_resolution__gte', 0), ('h3_resolution__lte', 15)), name='game_area_h3_resolution_valid'),
        ),
        migrations.AddIndex(
            model_name='runningrecord',
            index=models.Index(fields=['user', '-started_at'], name='running_rec_user_id_4d70f0_idx'),
        ),
        migrations.AddIndex(
            model_name='runningrecord',
            index=models.Index(fields=['room', 'user'], name='running_rec_room_id_384759_idx'),
        ),
        migrations.AddConstraint(
            model_name='runningrecord',
            constraint=models.CheckConstraint(check=models.Q(('duration_seconds__gte', 0)), name='record_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runningrecord',
            constraint=models.CheckConstraint(check=models.Q(('distance_meters__gte', 0)), name='record_distance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['creator', 'status'], name='rooms_creator_f54f11_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'start_date'], name='rooms_status_421d28_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('total_participants__gt', 0), ('total_participants__lte', 100)), name='room_total_participants_valid'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'team'], name='participant_room_id_f0976a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'is_host'], name='participant_room_id_49c9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'is_recording'], name='participant_room_id_87d468_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('paintball_count__gte', 0)), name='participant_paintball_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('super_paintball_count__gte', 0)), name='participant_super_paintball_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('paintball_gauge__gte', 0), ('paintball_gauge__lte', 100)), name='participant_gauge_valid'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('last_lat__isnull', True), models.Q(('last_lat__gte', -90), ('last_lat__lte', 90)), _connector='OR'), name='participant_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('last_lng__isnull', True), models.Q(('last_lng__gte', -180), ('last_lng__lte', 180)), _connector='OR'), name='participant_lng_range'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('room', 'user')},
        ),
    ]
