# Generated by Django 4.2.7 on 2026-01-26 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='room',
            field=models.ForeignKey(blank=True, help_text='초대하는 방 (방 초대일 때만)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='sender',
            field=models.ForeignKey(help_text='보낸 사람', on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['receiver', 'status'], name='mailbox_receive_b4593f_idx'),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['receiver', 'mail_type'], name='mailbox_receive_b268a1_idx'),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['receiver', '-created_at'], name='mailbox_receive_c7edde_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['requester', 'status'], name='friendships_request_74cfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['addressee', 'status'], name='friendships_address_4da91f_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(check=models.Q(('requester', models.F('addressee')), _negated=True), name='friendship_no_self_request'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('requester', 'addressee')},
        ),
    ]
